### ISSUE TITLE
Path error when checking drivers/rootkit  (handled ok) 

### ISSUE THREAD

**Issue by hollerith** [PwnDexter/SharpEDRChecker#1]
hey check out Vanguard caused this error LOL

````
[-] Errored on checking driver vgk.sys : \??\C:\Program Files\Riot Vanguard\vgk.sys
Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetFullPathWithAssert(String fileName)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at SharpEDRChecker.FileChecker.GetFileInfo(String filePath) in C:\Users\User\Documents\SharpEDRChecker\SharpEDRChecker\FileChecker.cs:line 14
   at SharpEDRChecker.DriverChecker.CheckDriver(String driverFileName, String driverBaseName) in C:\Users\User\Documents\SharpEDRChecker\SharpEDRChecker\DriverChecker.cs:line 96
[!] Could not get file info for: C:\Windows\Sysnative\drivers\dump_diskdump.sys
````

Nice work btw!

**Comment by PwnDexter** [comment]
Hey @hollerith thanks for raising this, I will get a look at it soon and update you 👍

**Comment by PwnDexter** [comment]
Hey @hollerith, this should now be resolved with the latest commit (https://github.com/PwnDexter/SharpEDRChecker/commit/235d490dc0561d0e93182bcb8c597a26eb3eeca8), I have tested it and it is all good, feel free to test yourself and let me know how it goes!

**Comment by hollerith** [comment]
Pulled it latest results has same error but in a different place? Also Vanguard is missing now. 

````
###################################################################################################
                    [!][!][!] Welcome to SharpEDRChecker by @PwnDexter [!][!][!]
[-][-][-] Not running as admin, some privileged metadata and processes may not be checked [-][-][-]
###################################################################################################

######################################
[!][!][!] Checking processes [!][!][!]
######################################

[-] Suspicious process found:
        Name: SecurityHealthService.exe
        Description: SecurityHealthService.exe
        Caption: SecurityHealthService.exe
        Binary:
        Process ID: 7420
        Parent Process: 948
        Process CmdLine:
        File Metadata:
[!] Matched on: securityhealthservice

[-] Errored on checking individual process: conhost.exe : 12200
Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetFullPathWithAssert(String fileName)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at SharpEDRChecker.FileChecker.GetFileInfo(String filePath) in C:\Users\User\Documents\SharpEDRChecker\SharpEDRChecker\FileChecker.cs:line 14
   at SharpEDRChecker.ProcessChecker.CheckProcess(ManagementBaseObject process) in C:\Users\User\Documents\SharpEDRChecker\SharpEDRChecker\ProcessChecker.cs:line 58
[-] Errored on checking individual process: conhost.exe : 14648
Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetFullPathWithAssert(String fileName)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at SharpEDRChecker.FileChecker.GetFileInfo(String filePath) in C:\Users\User\Documents\SharpEDRChecker\SharpEDRChecker\FileChecker.cs:line 14
   at SharpEDRChecker.ProcessChecker.CheckProcess(ManagementBaseObject process) in C:\Users\User\Documents\SharpEDRChecker\SharpEDRChecker\ProcessChecker.cs:line 58
[-] Suspicious process found:
        Name: MsMpEng.exe
        Description: MsMpEng.exe
        Caption: MsMpEng.exe
        Binary:
        Process ID: 14376
        Parent Process: 948
        Process CmdLine:
        File Metadata:
[!] Matched on: msmpeng

[-] Suspicious process found:
        Name: NisSrv.exe
        Description: NisSrv.exe
        Caption: NisSrv.exe
        Binary:
        Process ID: 6672
        Parent Process: 948
        Process CmdLine:
        File Metadata:
[!] Matched on: nissrv

[-] Suspicious process found:
        Name: smartscreen.exe
        Description: smartscreen.exe
        Caption: smartscreen.exe
        Binary: C:\Windows\System32\smartscreen.exe
        Process ID: 7304
        Parent Process: 700
        Process CmdLine: C:\Windows\System32\smartscreen.exe -Embedding
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\Windows\System32\smartscreen.exe
                 Original Filename: smartscreen.exe.mui
                 Internal Name: smartscreen.exe
                 Company Name: Microsoft Corporation
                 File Description: Windows Defender SmartScreen
                 Product Version: 10.0.19041.444
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: defender

###################################################################
[!][!][!] Checking modules loaded in your current process [!][!][!]
###################################################################

[-] Suspicious modload found in your process:
        Suspicious Module: C:\WINDOWS\SYSTEM32\amsi.dll
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\WINDOWS\SYSTEM32\amsi.dll
                 Original Filename: amsi.dll
                 Internal Name: amsi.dll
                 Company Name: Microsoft Corporation
                 File Description: Anti-Malware Scan Interface
                 Product Version: 10.0.19041.1
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: amsi.dll, anti-malware, malware

[-] Suspicious modload found in your process:
        Suspicious Module: C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2008.4-0\MpOav.dll
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2008.4-0\MpOav.dll
                 Original Filename: MpOAV.dll
                 Internal Name: MpOAV
                 Company Name: Microsoft Corporation
                 File Description: IOfficeAntiVirus Module
                 Product Version: 4.18.2008.4
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: antivirus, defender

########################################
[!][!][!] Checking Directories [!][!][!]
########################################

[-] Suspicious directory found: C:\Program Files\Windows Defender
[!] Matched on: defender

[-] Suspicious directory found: C:\Program Files\Windows Defender Advanced Threat Protection
[!] Matched on: defender, threat

[-] Suspicious directory found: C:\Program Files\Wireshark
[!] Matched on: wireshark

[-] Suspicious directory found: C:\Program Files (x86)\Windows Defender
[!] Matched on: defender

#####################################
[!][!][!] Checking Services [!][!][!]
#####################################

[-] Suspicious service found:
        Name: mpssvc
        DisplayName: Windows Defender Firewall
        Description: Windows Defender Firewall helps to protect your computer by preventing unauthorised users from gaining access to your computer through the Internet or a network.
        Caption: Windows Defender Firewall
        Binary: C:\WINDOWS\system32\svchost.exe -k LocalServiceNoNetworkFirewall -p
        Status: Running
        Process ID: 3040
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\WINDOWS\system32\svchost.exe
                 Original Filename: svchost.exe.mui
                 Internal Name: svchost.exe
                 Company Name: Microsoft Corporation
                 File Description: Host Process for Windows Services
                 Product Version: 10.0.19041.444
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: defender

[-] Suspicious service found:
        Name: PolicyAgent
        DisplayName: IPsec Policy Agent
        Description: Internet Protocol security (IPsec) supports network-level peer authentication, data origin authentication, data integrity, data confidentiality (encryption), and replay protection.  This service enforces IPsec policies created through the IP Security Policies snap-in or the command-line tool "netsh ipsec".  If you stop this service, you may experience network connectivity issues if your policy requires that connections use IPsec.  Also,remote management of Windows Defender Firewall is not available when this service is stopped.
        Caption: IPsec Policy Agent
        Binary: C:\WINDOWS\system32\svchost.exe -k NetworkServiceNetworkRestricted -p
        Status: Running
        Process ID: 5100
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\WINDOWS\system32\svchost.exe
                 Original Filename: svchost.exe.mui
                 Internal Name: svchost.exe
                 Company Name: Microsoft Corporation
                 File Description: Host Process for Windows Services
                 Product Version: 10.0.19041.444
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: defender

[-] Suspicious service found:
        Name: SecurityHealthService
        DisplayName: Windows Security Service
        Description: Windows Security Service handles unified device protection and health information
        Caption: Windows Security Service
        Binary: C:\WINDOWS\system32\SecurityHealthService.exe
        Status: Running
        Process ID: 7420
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\WINDOWS\system32\SecurityHealthService.exe
                 Original Filename: SecurityHealthService.exe
                 Internal Name: SecurityHealthService
                 Company Name: Microsoft Corporation
                 File Description: Windows Security Health Service
                 Product Version: 4.18.1907.16384
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: securityhealthservice

[-] Suspicious service found:
        Name: Sense
        DisplayName: Windows Defender Advanced Threat Protection Service
        Description: Windows Defender Advanced Threat Protection service helps protect against advanced threats by monitoring and reporting security events that happen on the computer.
        Caption: Windows Defender Advanced Threat Protection Service
        Binary: "C:\Program Files\Windows Defender Advanced Threat Protection\MsSense.exe"
        Status: Stopped
        Process ID: 0
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\Program Files\Windows Defender Advanced Threat Protection\MsSense.exe
                 Original Filename: MsSense.exe.mui
                 Internal Name: MsSense.exe
                 Company Name: Microsoft Corporation
                 File Description: Windows Defender Advanced Threat Protection Service Executable
                 Product Version: 10.7430.19041.444
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: defender, threat

[-] Suspicious service found:
        Name: WdNisSvc
        DisplayName: Microsoft Defender Antivirus Network Inspection Service
        Description: Helps guard against intrusion attempts targeting known and newly discovered vulnerabilities in network protocols
        Caption: Microsoft Defender Antivirus Network Inspection Service
        Binary: "C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2008.4-0\NisSrv.exe"
        Status: Running
        Process ID: 6672
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2008.4-0\NisSrv.exe
                 Original Filename: NisSrv.exe
                 Internal Name: NisSrv.exe
                 Company Name: Microsoft Corporation
                 File Description: Microsoft Network Realtime Inspection Service
                 Product Version: 4.18.2008.4
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: antivirus, defender, nissrv

[-] Suspicious service found:
        Name: WinDefend
        DisplayName: Microsoft Defender Antivirus Service
        Description: Helps protect users from malware and other potentially unwanted software
        Caption: Microsoft Defender Antivirus Service
        Binary: "C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2008.4-0\MsMpEng.exe"
        Status: Running
        Process ID: 14376
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2008.4-0\MsMpEng.exe
                 Original Filename: MsMpEng.exe
                 Internal Name: MsMpEng.exe
                 Company Name: Microsoft Corporation
                 File Description: Antimalware Service Executable
                 Product Version: 4.18.2008.4
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: antimalware, antivirus, defender, malware, msmpeng

[-] Suspicious service found:
        Name: wscsvc
        DisplayName: Security Center
        Description: The WSCSVC (Windows Security Center) service monitors and reports security health settings on the computer.  The health settings include firewall (on/off), antivirus (on/off/out of date), antispyware (on/off/out of date), Windows Update (automatically/manually download and install updates), User Account Control (on/off), and Internet settings (recommended/not recommended). The service provides COM APIs for independent software vendors to register and record the state of their products to the Security Center service.  The Security and Maintenance UI uses the service to provide systray alerts and a graphical view of the security health states in the Security and Maintenance control panel.  Network Access Protection (NAP) uses the service to report the security health states of clients to the NAP Network Policy Server to make network quarantine decisions.  The service also has a public API that allows external consumers to programmatically retrieve the aggregated security health state of the system.
        Caption: Security Center
        Binary: C:\WINDOWS\System32\svchost.exe -k LocalServiceNetworkRestricted -p
        Status: Running
        Process ID: 1340
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: C:\WINDOWS\System32\svchost.exe
                 Original Filename: svchost.exe.mui
                 Internal Name: svchost.exe
                 Company Name: Microsoft Corporation
                 File Description: Host Process for Windows Services
                 Product Version: 10.0.19041.444
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: antivirus

[!] Could not get file info for: C:

####################################
[!][!][!] Checking drivers [!][!][!]
####################################

[!] Could not get file info for: c:\Windows\Sysnative\drivers\dump_diskdump.sys

[!] Could not get file info for: c:\Windows\Sysnative\drivers\dump_storahci.sys

[!] Could not get file info for: c:\Windows\Sysnative\drivers\dump_dumpfve.sys

[-] Suspicious driver found:
        Suspicious Module: WdFilter.sys
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: c:\windows\system32\drivers\wd\wdfilter.sys
                 Original Filename: WdFilter.sys
                 Internal Name: WdFilter
                 Company Name: Microsoft Corporation
                 File Description: Microsoft antimalware file system filter driver
                 Product Version: 4.18.2008.4
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: antimalware, malware

[-] Suspicious driver found:
        Suspicious Module: WdNisDrv.sys
        File Metadata:
                 Product Name: Microsoft® Windows® Operating System
                 Filename: c:\windows\system32\drivers\wd\wdnisdrv.sys
                 Original Filename: wdnisdrv.sys
                 Internal Name: wdnisdrv.sys
                 Company Name: Microsoft Corporation
                 File Description: Windows Defender Network Stream Filter
                 Product Version: 4.18.2008.4
                 Comments:
                 Legal Copyright: © Microsoft Corporation. All rights reserved.
                 Legal Trademarks:
[!] Matched on: defender

################################
[!][!][!] TLDR Summary [!][!][!]
################################

[!] Process Summary:
        [-] SecurityHealthService.exe : securityhealthservice
        conhost.exe : Failed to perform checks
        conhost.exe : Failed to perform checks
        [-] MsMpEng.exe : msmpeng
        [-] NisSrv.exe : nissrv
        [-] smartscreen.exe : defender


[!] Modload Summary:
        [-] C:\WINDOWS\SYSTEM32\amsi.dll : amsi.dll, anti-malware, malware
        [-] C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2008.4-0\MpOav.dll : antivirus, defender


[!] Directory Summary:
        [-] C:\Program Files\Windows Defender : defender
        [-] C:\Program Files\Windows Defender Advanced Threat Protection : defender, threat
        [-] C:\Program Files\Wireshark : wireshark
        [-] C:\Program Files (x86)\Windows Defender : defender


[!] Service Summary:
        [-] mpssvc : defender
        [-] PolicyAgent : defender
        [-] SecurityHealthService : securityhealthservice
        [-] Sense : defender, threat
        [-] WdNisSvc : antivirus, defender, nissrv
        [-] WinDefend : antimalware, antivirus, defender, malware, msmpeng
        [-] wscsvc : antivirus


[!] Driver Summary:
        [-] WdFilter.sys : antimalware, malware
        [-] WdNisDrv.sys : defender

#######################################
[!][!][!] EDR Checks Complete [!][!][!]
#######################################

````

**Comment by PwnDexter** [comment]
Hey, 

I have added an additional catch for the problem above, the current issue is we/I can't see the path that its trying to read which contains the illegal characters so the new catch should print out the path and I can get a look. The latest commit (https://github.com/PwnDexter/SharpEDRChecker/commit/70db10ce0d2922b978352dee91392cf809dac2af) has this added, if you can run the latest version and show me the output for the two processes that caused the error that would be super helpful. Than I can look at handling whatever the illegal characters are.

As for Vanguard no longer appearing that is because it is not an EDR software, just Riot's anti-cheat software so not relevant to situational awareness, the only reason it showed up the first time was due to the illegal characters in the driver path.

Let me know how you get on!

Cheers

**Comment by hollerith** [comment]
Perfection!
